image: 
  file: .gitpod.dockerfile

tasks:
  - name: sqlserver and api server starter
    before: sudo 

  # TODO setup the api server start 
  # - name: Flutter 
    # before:  flutter pub get && flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
    


ports:
  - port: 8080
    onOpen: open-browser