image: 
  file: .gitpod.dockerfile

tasks:

  - name: Flutter 
    before: sudo chown -R $(whoami) /  && flutter pub get && flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
    


ports:
  - port: 8080
    onOpen: open-browser