image: 
  file: .gitpod.dockerfile

tasks:
  
     

  - name: python webserver
    before: 
      >
        sudo apt-get install -y libpq-dev python-dev &&
        cd sqlstarter && 
        chmod +x ./sqlstarter.sh &&
        sudo ./sqlstarter.sh &&
        cd ..  &&
        cd backend &&
        pip3 install virtualenv &&
        python3 -m virtualenv interpreter &&
        source ./interpreter/bin/activate &&
        pip3 install -r requirements.txt  &&
        uvicorn main:app --reload --host 0.0.0.0 --port 6969


  # TODO setup the api server start 
  - name: Flutter 
    before:
      >
        git config --global --add safe.directory /sdks/flutter/ &&
        sudo chown -R $(whoami) /sdks/flutter/ &&  
        sudo chown -R $(whoami) /root/ && 
        flutter pub get &&
        flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
    


ports:
  - port: 8080
    onOpen: open-browser
  
  - port: 6969
    onOpen:  open-preview
  