export 'package:classify/screens/admin/admin_home.dart';
export 'package:classify/screens/admin/features/manage_courses.dart';
export 'package:classify/screens/admin/signup.dart';
export 'package:classify/screens/common/role_selection.dart';
export 'package:classify/screens/common/signin.dart';
export 'package:classify/screens/parent/parent_home.dart';
export 'package:classify/screens/student/studenthome/student_home.dart';
export 'package:classify/screens/student/attendenceandtest/studentstats.dart';
export 'package:classify/screens/teacher/signup.dart';
export 'package:classify/screens/teacher/teacherhome/teacher_home.dart';
export 'package:classify/screens/teacher/institution interface/institionmain.dart';
export 'package:classify/screens/teacher/attendance/attendance.dart';
